<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SHELW42SLPC0883" name="Default test" tests="8" failures="1" timestamp="9 Sep 2019 13:32:02 GMT" time="259.869" errors="0">
  <testcase name="ValidateHomePage" time="0.076" classname="com.Shell.qa.TestCases.TC02_HomePageTest"/>
  <testcase name="ValidateOrderaCardLink" time="0.08" classname="com.Shell.qa.TestCases.TC02_HomePageTest"/>
  <testcase name="ValidateBlockCardLink" time="0.06" classname="com.Shell.qa.TestCases.TC02_HomePageTest"/>
  <testcase name="ValidateCancelCardLink" time="0.088" classname="com.Shell.qa.TestCases.TC02_HomePageTest"/>
  <testcase name="ValidateCardActivityLink" time="0.06" classname="com.Shell.qa.TestCases.TC02_HomePageTest"/>
  <testcase name="ValidateCardsLink" time="0.068" classname="com.Shell.qa.TestCases.TC02_HomePageTest"/>
  <testcase name="ValidateFinanceLink" time="0.064" classname="com.Shell.qa.TestCases.TC02_HomePageTest"/>
  <testcase name="HomeTest" time="20.243" classname="com.Shell.qa.TestCases.TC02_HomePageTest">
    <failure type="java.lang.AssertionError" message="On clicking cards from home page, unsuccessful to move to Cards Page">
      <![CDATA[java.lang.AssertionError: On clicking cards from home page, unsuccessful to move to Cards Page
	at org.testng.Assert.fail(Assert.java:94)
	at com.Shell.qa.TestCases.TC02_HomePageTest.HomeTest(TC02_HomePageTest.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- HomeTest -->
</testsuite> <!-- Default test -->
